### ISSUE TITLE
Image size with itk

### ISSUE THREAD

**Issue by tbaudier** [OpenGATE/GateTools#2]
Hi @djboersma,

I'm currently reading your code and I saw you created a function to get the size of the image with itk:
https://github.com/OpenGATE/GateTools/blob/34fc70a4f4dbe247516e12e3ff04631d67770c65/gatetools/image_arithm.py#L48

You can use to have the size of the i<sup>th</sup> of the image
```
image.GetLargestPossibleRegion().GetSize()[i]
```

Thomas

**Comment by SimonRit** [comment]
Not that [line](https://github.com/OpenGATE/GateTools/blob/34fc70a4f4dbe247516e12e3ff04631d67770c65/gatetools/image_arithm.py#L54) will return a shape with x in the last dimension, y in the before last, etc. For example
```
>>> import itk
>>> img = itk.Image[itk.F,3].New()
>>> img.SetRegions([256,255,254])
>>> img.Allocate()
>>> print(img.GetLargestPossibleRegion().GetSize())
itkSize3 ([256, 255, 254])
>>> itk.GetArrayViewFromImage(img).shape
(254, 255, 256)

```

**Comment by djboersma** [comment]
Hm. I have always worked with SimpleITK and with sitk I knew that the numpy array returned by sitk.GetArrayFromImage was backwards (indices [z,y,x]), but when I tried to make stuff work with "non-simple" itk it looked like the array shape was "normal" ([x,y,z]). However, I must have been seriously confused somehow, because now that I check again, I see that you are correct, "GetArrayViewFromImage" returns a backwards numpy array for both "itk" and "sitk". Unfortunately.

Anyway, as Thomas pointed out, I do not need this function anymore, because I can use this "GetLargestPossibleRegion" method to get the "GetSize" functionality.
